package com.example.solar.matching.domain;


public enum MatchStatus {
    SUGGESTED,    // Initial match generated by algorithm
    VIEWED,       // Customer viewed the professional
    CONTACTED,    // Customer contacted the professional
    REJECTED      // Customer rejected the match
}
